# Generated by Django 5.0.6 on 2024-06-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0003_alter_pelicula_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(default=2, upload_to='peliculas/'),
            preserve_default=False,
        ),
    ]
