# Generated by Django 5.0.6 on 2024-06-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0005_alter_pelicula_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen_fondo',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_fondo'),
        ),
    ]
