# Generated by Django 5.0.6 on 2024-06-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0006_pelicula_imagen_fondo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_fondo', models.ImageField(blank=True, null=True, upload_to='imagenes_fondo')),
            ],
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='imagen_fondo',
        ),
    ]
