# Generated by Django 5.0.6 on 2024-06-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misitio', '0008_configuracionlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_fondo_registro', models.ImageField(blank=True, null=True, upload_to='fondos_registro/')),
            ],
        ),
    ]
